dimensions:
  # dimension of latent space
  latent: 100
  # (width, height, nr_channels) of images
  img_shape: !!python/tuple [28, 28, 1]

models:
  # path to weights of models
  butterfly: "tf_models/DCGAN-Butterfly"

images:
  # location of directories to images
  real_project_path: "project/static/images/real"
  real_url_path: "/static/images/real"

game:
  rounds: 10